- name: update web servers
  hosts: asgard
  remote_user: root
  become: true
  vars:
    container_image: qubedprince/dealerform-image
    service_name : dealform-web

  tasks:
  - name: ensure nginx is at the latest version
    yum:
      name: nginx
      state: latest

  - name: Install python3-pip  (state=present is optional)
    yum:
      name: python3-pip
      state: present

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull Docker Image
    docker_image:
      name: '{{container_image}}'
      source: pull

  - name: Update Service
    command: docker service update --force --detach=false --update-parallelism=1 --update-delay=100s --update-failure-action=rollback --update-order=start-first  --image '{{container_image}}' '{{service_name }}'

